ads/urls.py
from django.urls import path
from guest_user.decorators import allow_guest_user

from ads import views

app_name = 'ads'
urlpatterns = [
    path('', allow_guest_user(views.IndexView()), name='index'),
    path('search/autocomplete/', allow_guest_user(views.autocomplete), name='autocomplete'),
    path('url/', views.to_external_url, name='to_external_url'),
    path('ads/<str:category>/<str:subcategory>', views.AdsByCategoriesView.as_view(), name='list_by_categories'),
    path('ads/<str:category>', views.AdsByMainCategoryView.as_view(), name='list_by_main_category'),
    path('view/<str:ad_slug>-<int:id>/', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('my_ads/', views.user_ads, name='user_ads'),

]

comohay/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from comohay import settings

urlpatterns = [
    path("convert/", include("guest_user.urls")),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('', include('ads.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models/adimages.py
from django.db import models
from django.db.models.signals import post_init, post_save, pre_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from ads.models.ad import Ad


class AdImage(models.Model):
    ad = models.ForeignKey(Ad, default=None, on_delete=models.CASCADE, verbose_name=_('Ad'))
    image = models.ImageField(verbose_name=_('Image'))

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')


@receiver(post_init, sender=AdImage)
def backup_image_path(sender, instance, **kwargs):
    if (instance.id is not None):
        instance._current_image_file = instance.image


@receiver(post_save, sender=AdImage)
def delete_old_image(sender, instance, **kwargs):
    if hasattr(instance, '_current_image_file'):
        if instance._current_image_file.path != instance.image.path:
            instance._current_image_file.delete(save=False)


@receiver(pre_delete, sender=AdImage)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)

ads/forms/adform.py
from categories.models import Category
from django.forms import ModelForm
from django_filters.fields import ModelChoiceField

from ads.models.ad import Ad


class AdForm(ModelForm):

    category = ModelChoiceField(Category.objects.exclude(parent=None).all())

    class Meta:
        model = Ad
        exclude = [
            'slug',
            'external_source',
            'external_id',
            'external_url',
            'created_at',
            'updated_at',
            'created_by',
            'created_at',
        ]

ads/forms/adimageform.py
from django.forms import ModelForm, ImageField, FileInput
from django.utils.translation import gettext_lazy as _
from ads.models.adimages import AdImage


class AdImageForm(ModelForm):

    image = ImageField(label=_('Image'))

    class Meta:
        model = AdImage
        fields = ('image',)

ads/forms/adsearchform.py
import sys

from haystack.forms import ModelSearchForm
from haystack.inputs import AltParser

from ads.models import Ad, Province
from django import forms


class AdSearchForm(ModelSearchForm):
    provinces = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Province.objects.all(),
        to_field_name='name'
    )

    price_from = forms.IntegerField(required=False)
    price_to = forms.IntegerField(required=False)
    price_currency = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.sqs = None

    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        q = self.cleaned_data['q']

        provinces = self.cleaned_data['provinces']
        price_from = self.cleaned_data['price_from']
        price_to = self.cleaned_data['price_to']
        price_currency = self.cleaned_data['price_currency']

        # boosting of 1.5 for every term that appears in the title
        # TODO: improve this by overriding the solr backend method build_alt_parser_query in order to avoid to do the
        #  escaping twice. It will be recommended in order to avoid triple escaping in the boost query(bq) to build the
        #  query with the defType parameter instead of the LocalParams syntax that is currently being in use by the
        #  build_alt_parser_query method.
        bq = self.create_boosting_query(q)

        # boost multiplier by age. This solr function will return a number between 1 an 0, the older the ad the lower
        # the number. Please refer to
        #   https://lucene.apache.org/solr/guide/7_7/function-queries.html
        #   https://lucene.apache.org/core/6_6_0/queries/org/apache/lucene/queries/function/valuesource/ReciprocalFloatFunction.html and
        #   https://www.youtube.com/watch?v=3E8jOUgj6L8to
        boost = "recip(ms(NOW,external_created_at),3.16e-11,1,1)"

        pf = "title^2.5 description^0.15"
        pf3 = "title^1.5 description^0.10"
        pf2 = "title^0.5 description^0.05"

        sqs = self.searchqueryset.filter(
            content=AltParser('edismax', q, bq=bq, boost=boost, pf=pf, pf3=pf3, pf2=pf2, ps=2, ps3=2, ps2=1))

        if provinces.count() > 0:
            sqs = sqs.filter_and(province__in=provinces.values_list('name', flat=True))

        if price_from and price_to:
            sqs = sqs.filter_and(price__range=[price_from, price_to])
        elif price_from:
            sqs = sqs.filter_and(price__range=[price_from, sys.maxsize])
        elif price_to:
            sqs = sqs.filter_and(price__range=[0, price_to])

        if price_from or price_to:
            sqs = sqs.filter_and(currency_iso=price_currency)

        # TODO: add flag to allow to search trough removed ads
        if True:
            sqs = sqs.filter_and(is_deleted=False)

        if self.load_all:
            sqs = sqs.load_all()

        return sqs.models(Ad)

    def create_boosting_query(self, query):
        # Removing '"' because its not necessary for query boosting
        query = query.replace('"', '')

        clean_q = self.triple_clean(query)
        clean_q = clean_q.replace("'", "\\\\'")

        # this will add the field to search and the boosting value for each term.
        # Eg. 'split royal' -> 'title:split^1.5 title:royal^1.5 description:split^1.1 description:royal^1.1'
        return 'title:' + clean_q.replace(' ', '^1.5 title:') + '^1.5' + ' description:' + clean_q.replace(' ',
                                                                                                           '^0.1 description:') + '^0.1'

    def triple_clean(self, query_fragment):
        """
        Provides a mechanism for sanitizing user input before presenting the
        value to the backend.

        A basic (override-able) implementation is provided.
        """
        backend = self.searchqueryset.query.backend

        if not isinstance(query_fragment, str):
            return query_fragment

        words = query_fragment.split()
        cleaned_words = []

        for word in words:
            if word in backend.RESERVED_WORDS:
                word = word.replace(word, word.lower())

            for char in backend.RESERVED_CHARACTERS:
                word = word.replace(char, "\\\\\\\\%s" % char)

            cleaned_words.append(word)

        return " ".join(cleaned_words)

ads/views.py
import logging
import re
from encodings.base64_codec import base64_decode

from actstream import action
from categories.models import Category
from django.contrib.auth.decorators import login_required
from django.core.cache import caches
from django.core.exceptions import ValidationError
from django.forms import modelformset_factory, inlineformset_factory
from django.http import HttpResponseRedirect, Http404, HttpResponseBadRequest, JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator

from django_filters.views import FilterView
from guest_user.decorators import allow_guest_user
from haystack.views import SearchView
from meta.views import Meta
from rest_framework.utils import json
from text_unidecode import unidecode

from ads.actions import ACTION_FOLLOW_EXTERNAL_AD, ACTION_VIEW_AD, ACTION_SEARCH_AD
from ads.filters.ad_filter import AdFilter
from ads.forms.adform import AdForm
from ads.forms.adimageform import AdImageForm
from ads.forms.adsearchform import AdSearchForm
from ads.helpers.telegrambot import TelegramBot
from ads.models import UserSearch, Province
from ads.models.ad import Ad
from ads.models.adimages import AdImage
from comohay import settings

logger = logging.getLogger(__name__)


class IndexView(SearchView):
    template = 'ad/index.html'

    def __init__(self, template=None, load_all=True, form_class=None, searchqueryset=None, results_per_page=None):
        super().__init__(template, load_all, form_class, searchqueryset, results_per_page)
        if form_class is None:
            self.form_class = AdSearchForm

    def __call__(self, request):
        cache = caches['search']
        path = request.get_full_path()

        self.request = request
        self.form = self.build_form()
        self.query = self.get_query()
        self.results = self.get_results()

        response = cache.get(path)
        if not response:
            response = self.create_response()
            cache.set(path, response, settings.CACHE_SEARCH_RESPONSE_SECONDS)
        if self.query != '' and not self.request.GET.get('page', False) and not request.user.is_anonymous:
            user_search = UserSearch(user=request.user, search=self.query,
                                     autosuggestion=bool(request.GET.get('a', False)))
            user_search.save()
            action.send(request.user, verb=ACTION_SEARCH_AD, target=user_search)
        return response

    def get_context(self):
        context = super().get_context()
        result_count = self.results.count()
        #TODO: solr is throwing a java.lang.NumberFormatException when there is no results, but it seems to not have any
        # negative effect, it could be the Spellchecker
        context['index_count'] = result_count if self.query != '' else Ad.objects.count()

        context['all_provinces'] = Province.objects.all()
        context['all_currencies'] = Ad.ALLOWED_CURRENCIES

        if self.query:
            context['price_from'] = self.form.cleaned_data['price_from']
            context['price_to'] = self.form.cleaned_data['price_to']
            context['price_currency'] = self.form.cleaned_data['price_currency']
            context['selected_provinces'] = self.form.cleaned_data['provinces']

        base_query_dict = self.request.GET.copy()
        if 'page' in base_query_dict:
            del base_query_dict['page']
        context['base_query'] = base_query_dict.urlencode()

        # Before split the query its necessary to remove the '"' characters because those are part of the syntax to
        # phrase query
        query_split = self.query.replace('"', '').split(' ')

        def find_missing_terms(search_result):
            missing_terms = []
            for term in query_split:
                if not re.search(re.escape(unidecode(term)), unidecode(search_result.text), re.IGNORECASE):
                    missing_terms.append(term)

            search_result.__dict__['missing_terms'] = missing_terms
            return search_result

        context['page'].object_list = map(find_missing_terms, context['page'].object_list)

        meta = Meta(
            keywords=['indexado de clasificados en cuba', 'búsqueda de clasificados en cuba',
                      'cuba indexado de clasificados', 'cuba búsqueda de clasificados',
                      'indexado de anuncios en cuba', 'búsqueda de anuncios en cuba',
                      'cuba indexado de anuncios', 'cuba búsqueda de anuncios'
                      ],
            image=settings.STATIC_URL + 'logo-vertical-adjusted.png',
            image_width=600,
            image_height=600,
            url=self.request.get_full_path(),
            title=settings.META_SITE_NAME,
            description='La manera más eficiente de buscar clasificados en Cuba, rápido y ligero. Indexamos constantemente los sitos más populares de anuncios en nuestro país.',
        )

        if self.query != '':
            meta.title = '{} - {}'.format(self.query, settings.META_SITE_NAME)
            meta.description = "Consulta los resultados para \"{}\" que hemos encontrado. Indexamos constantemente los sitios cubanos de anuncios más populares para ofrecerte los mejores resultados.".format(
                self.query)

        context['meta'] = meta
        return context


def autocomplete(request):
    query = request.GET.get('q', '')

    suggestions = settings.autocomplete.search(query, max_cost=3, size=7)

    for pos in range(len(suggestions)):
        if type(suggestions[pos]) != str:
            suggestions[pos] = ' '.join(suggestions[pos])

    the_data = json.dumps({
        'results': suggestions
    })

    return HttpResponse(the_data, content_type='application/json')


class AdsByMainCategoryView(FilterView):
    paginate_by = 20
    model = Ad
    template_name = 'ad/ads.html'
    filterset_fields = '__all__'
    category: Category

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.category = get_object_or_404(Category, slug=self.kwargs['category'], parent=None)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['category'] = self.category

        return context

    @method_decorator(allow_guest_user)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class AdsByCategoriesView(FilterView):
    paginate_by = 20
    model = Ad
    template_name = 'ad/ads.html'
    filterset_fields = '__all__'
    category: Category
    subcategory: Category

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.category = get_object_or_404(Category, slug=self.kwargs['category'])
        try:
            self.subcategory = Category.objects.filter(slug=self.kwargs['subcategory'], parent=self.category.id).get()
        except Category.DoesNotExist:
            raise Http404('No categories matches the given query.')

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-created_at')
        return queryset.filter(category=self.subcategory.id)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['category'] = self.category
        context['subcategory'] = self.subcategory

        return context

    @method_decorator(allow_guest_user)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@allow_guest_user
def detail(request, id, ad_slug):
    ad = get_object_or_404(Ad, id=id, slug=ad_slug)
    action.send(request.user, verb=ACTION_VIEW_AD, target=ad)
    return render(request, 'ad/detail.html', {'ad': ad})


@allow_guest_user
# @csrf_exempt
def create(request):
    image_form_set = modelformset_factory(AdImage, form=AdImageForm, extra=3)

    if request.method == 'POST':
        ad_form = AdForm(request.POST)
        ad_image_formset = image_form_set(
            request.POST,
            request.FILES,
            queryset=AdImage.objects.none()
        )

        if ad_form.is_valid() and ad_image_formset.is_valid():
            ad = ad_form.save()
            for form in ad_image_formset.cleaned_data:
                if 'image' in form:
                    image = form['image']
                    ad_image = AdImage(ad=ad, image=image)
                    ad_image.save()

            try:
                TelegramBot.broadcast_ad(ad, request)
            except Exception as e:
                logger.error('Error broadcasting AD: ' + str(e))

            if request.user.is_authenticated:
                return HttpResponseRedirect('/my_ads')
            return HttpResponseRedirect('/')
    else:
        ad_form = AdForm()
        ad_image_formset = image_form_set(queryset=AdImage.objects.none())
    return render(request, 'ad/create.html', {'ad_form': ad_form, 'ad_image_formset': ad_image_formset})


@allow_guest_user
def to_external_url(request):
    url = request.GET.get('url')
    ref = request.GET.get('ref')
    request_ad = request.GET.get('ad')
    from_url = base64_decode(bytes(ref, 'utf-8'))[0].decode('utf-8')
    ad_id = base64_decode(bytes(request_ad, 'utf-8'))[0].decode('utf-8')
    ad = get_object_or_404(Ad, id=ad_id)
    if not url or not from_url or not from_url.startswith(request.build_absolute_uri('/')) or not ad:
        return HttpResponseBadRequest()
    response = HttpResponseRedirect(url)
    response['Referer'] = from_url
    if not request.user.is_anonymous:
        action.send(request.user, verb=ACTION_FOLLOW_EXTERNAL_AD, target=ad)
    return response


@login_required
def user_ads(request):

ads/templates/ad/_filters-container.html
{% load i18n %}
<div id="filters-container" class="d-none">
    <div class="container">
        <div id="provinces-filter">
            <label for="provinces-select">{% trans "Provinces" %}:</label>
            <select id="provinces-select" name="provinces" multiple class="d-none">
                {% for province in all_provinces %}
                    <option value="{{ province.name }}"
                            {% if province in selected_provinces %}selected{% endif %}>{{ province.name }}</option>
                {% endfor %}
            </select>
            <div class="row custom-select">
                {% for province in all_provinces %}
                    <div class="column column-xs-100 column-sm-50 column-md-25">
                        <button class="button button-sm button-outline"
                                type="button"
                                data-selected="{% if province in selected_provinces %}1{% else %}0{% endif %}"
                                data-value="{{ province.name }}">{{ province.display_name }}</button>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div id="prices-filter">
            <label>{% trans "Prices" %}:</label>
            <div class="row">
                <div class="column column-30">
                    <input type="number" name="price_from" placeholder="{% trans 'From' %}"
                           onkeypress="return isNumberKey(event)"
                           {% if price_from is not empty %}value="{{ price_from }}{% endif %}">
                </div>
                <div class="column column-30">
                    <input type="number" name="price_to" placeholder="{% trans 'To' %}"
                           onkeypress="return isNumberKey(event)"
                           {% if price_to is not empty %}value="{{ price_to }}{% endif %}">
                </div>
                <div class="column column-30">
                    <select name="price_currency">
                        {% for currency in all_currencies %}
                            <option value="{{ currency.0 }}"
                                    {% if currency.0 == price_currency %}selected{% endif %}>{{ currency.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <button type="submit" class="button button-sm float-right"
                style="margin-top: 1rem;margin-bottom: 1rem;">{% trans "Search" %}</button>
    </div>
</div>

ads/templates/ad/_filters-selected.html
{% load i18n %}
<div class="filters-selected">
    <div id="prices-selected" class="row">
        {% if price_from is not empty %}
            <div class="item-container column column-xs-100 column-sm-50">
                <div class="item">
                    <button type="button"
                            class="remove-filter button button-sm button-clear"
                            data-reference="price_from"
                            onclick="window.search_filter_manager.removePriceSelection(this.getAttribute('data-reference'))">
                        <span class="icon-cancel-1"></span></button>
                    {% trans 'From' %}: {{ price_from }} {{ price_currency }}
                </div>
            </div>
        {% endif %}
        {% if price_to is not empty %}
            <div class="item-container column column-xs-100 column-sm-50">
                <div class="item">
                    <button type="button"
                            class="remove-filter button button-sm button-clear"
                            data-reference="price_to"
                            onclick="window.search_filter_manager.removePriceSelection(this.getAttribute('data-reference'))">
                        <span class="icon-cancel-1"></span></button>
                    {% trans 'To' %}: {{ price_to }} {{ price_currency }}
                </div>
            </div>
        {% endif %}
    </div>
    <div id="provinces-selected" class="row">
        {% for province in selected_provinces %}
            <div class="item-container column column-xs-100 column-sm-50">
                <div class="item">
                    <button type="button"
                            class="remove-filter button button-sm button-clear"
                            data-reference="{{ province.name }}">
                        <span class="icon-cancel-1"></span></button>
                    {{ province.display_name }}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

ads/templates/ad/_list-item-back.html
{% load highlight %}

<div class="list-item-container">
    {% if back %}
        <a href="{% url "ads:edit" id=ad.id %}" class="button button-outline button-sm"><span
                class="icon-pencil"></span> Editar</a>
        <button class="button button-outline button-sm ajax-delete"
                data-delete-url="{% url "ads:delete" id=ad.id %}"><span class="icon-trash"></span> Eliminar
        </button>
    {% elif ad.external_source %}
        <span class="list-item-badge badge badge-secondary">{{ ad.external_source }}</span>
    {% endif %}
    <div class="list-item-header">
        <a href="{{ ad.get_absolute_url }}" {% if ad.external_source %}target="_blank" class="external" rel="nofollow"
           data-goto="{{ request.scheme }}://{{ request.get_host }}{% url "ads:to_external_url" %}"{% endif %}
           data-ad="{{ ad.id }}">
            <h4 class="list-item-title">{{ ad.title }}</h4>
            <span class="list-item-location">
                {% if ad.province %}{{ ad.province }}{% endif %}{% if ad.municipality %},{% endif %}
                {% if ad.municipality %}{{ ad.municipality }}{% endif %}
                ({{ ad.created_at | date:"SHORT_DATE_FORMAT" }})
            </span>
            {% if ad.price %}
                <h3 class="list-item-price">{{ ad.price }} {{ ad.currency_iso }}</h3>
            {% endif %}
        </a>
    </div>
    <div class="list-item-description">
        <p>
            {# text highlight for haystack results #}
            {% if query and result %}
                {% highlight result.description with query max_lenght 260 %}
            {% else %}
                {{ ad.description| truncatechars:260 }}
            {% endif %}
        </p>
    </div>

    {% if back %}
        <div class="list-telegram-switch">
            <!-- Rectangular switch -->
            {#                    <label class="switch">#}
            {#                        <input type="checkbox">#}
            {#                        <span class="slider"></span>#}
            {#                    </label>#}

            <!-- Rounded switch -->
            <label class="switch">
                <input type="checkbox">
                <span class="slider round"></span>
            </label>
            <label class="telegram-switch-label">Republicar en grupos de Telegram</label>
        </div>
    {% endif %}

</div>

ads/templates/ad/_list-item.html
{% load highlight %}
{% load i18n %}

<div class="list-item-container">
    <div class="list-item-header">
        {% if ad.external_source %}
            <span class="list-item-badge badge badge-secondary">{{ ad.external_source }}</span>
            {% if ad.external_created_at %}
                <span style="float: right; padding-top: 5px;">{{ ad.external_created_at | date:"SHORT_DATE_FORMAT" }}</span>
            {% endif %}
        {% elif ad.external_created_at  %}
              <span style="float: right; padding-top: 5px;">{{ ad.external_created_at | date:"SHORT_DATE_FORMAT" }}</span>
        {% endif %}
    </div>
    <div class="list-item-title">
        <a href="{{ ad.get_absolute_url }}" {% if ad.external_source %}target="_blank" class="external" rel="nofollow"
           data-goto="{{ request.scheme }}://{{ request.get_host }}{% url "ads:to_external_url" %}"{% endif %}
           data-ad="{{ ad.id }}">
            <h2>{{ ad.title }}</h2>
        </a>
    </div>
    <div class="list-item-location">
        <span>
                {% if ad.province %}{{ ad.province }}{% endif %}{% if ad.municipality %},{% endif %}
                {% if ad.municipality %}{{ ad.municipality }}{% endif %}
            </span>
    </div>
    {% if ad.price %}
        <div class="list-item-price"><h3>{{ ad.price }} {{ ad.currency_iso }}</h3></div>
    {% endif %}
    <div class="list-item-description">
        <p>
            {# text highlight for haystack results #}
            {% if query and result %}
                {% highlight result.description with query max_lenght 260 %}
            {% else %}
                {{ ad.description| truncatechars:260 }}
            {% endif %}
        </p>
        {% if query and result and result.missing_terms %}
            <div>{% trans 'Missing' %}: {% for missing_term in result.missing_terms %}
                <span class="text-cross-out">{{ missing_term }}</span>{% endfor %}</div>
        {% endif %}
    </div>

    {% if back %}
        <div class="list-telegram-switch">
            <!-- Rectangular switch -->
            {#                    <label class="switch">#}
            {#                        <input type="checkbox">#}
            {#                        <span class="slider"></span>#}
            {#                    </label>#}

            <!-- Rounded switch -->
            <label class="switch">
                <input type="checkbox">
                <span class="slider round"></span>
            </label>
            <label class="telegram-switch-label">Republicar en grupos de Telegram</label>
        </div>
    {% endif %}

</div>

ads/templates/ad/detail.html
{% extends 'layout.html' %}
{% load more_like_this %}
{% load i18n %}
{% load static %}
{% load compress %}
{% load thumbnail %}

{% block css %}
    {% compress css %}
        <link type="text/x-scss" href="{% static 'img-lightbox/img-lightbox.scss' %}" rel="stylesheet">
        {#        <link type="text/x-scss" href="{% static 'glihtbox/glightbox.scss' %}" rel="stylesheet">#}
        {#        <link type="text/x-scss" href="{% static 'lightgallery/scss/lightgallery.scss' %}" rel="stylesheet">#}
    {% endcompress %}
{% endblock %}

{% block content %}
    <h3>{{ ad.title }}</h3>

    <div class="row">
        {% if ad.adimage_set.all %}
            <div class="column column-40 responsive">
                <div id="splide" class="splide">
                    <div class="splide__track">
                        <ul class="splide__list">
                            {% for ad_image in ad.adimage_set.all %}
                                {% thumbnail ad_image.image "300x300" crop="center" as im %}
                                    <li class="splide__slide lightgallery" style="text-align: center">
                                        <a href="{{ ad_image.image.url }}" class="img-lightbox-link"
                                           data-src="{{ ad_image.image.url }}"
                                           aria-hidden="true"
                                           rel="lightbox">
                                            <img src="{{ im.url }}" width="{{ im.width }}">
                                        </a>
                                    </li>
                                {% endthumbnail %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="column" style="margin-top: 5px">
            <span class="list-item-location">{{ ad.province }}, {{ ad.municipality }}</span>
            {% if ad.price %}
                <h4 class="list-item-price">{{ ad.price }} {{ ad.currency_iso }}</h4>
            {% endif %}
            <p class="text-justify">{{ ad.description }}</p>
            {% more_like_this ad as related_contents limit 5 %}
            {% if related_contents %}
                <h3>{% trans "You may also be interested in" %}:</h3>
                <ul>
                    {% for related_content in related_contents %}
                        <li>
                            <a href="{{ related_content.object.get_absolute_url }}">{{ related_content.object.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

    </div>

{% endblock %}

{% block js %}
    {% compress js %}
        <script type="text/javascript" src="{% static "splide/splide.js" %}"></script>
        {#        <script type="text/javascript" src="{% static "lightgallery/js/lightgallery.js" %}"></script>#}
        <script type="text/javascript" src="{% static "img-lightbox/img-lightbox.js" %}"></script>
        {#        <script type="text/javascript" src="{% static "glihtbox/glightbox.js" %}"></script>#}
    {% endcompress %}

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            new Splide('#splide', {
                arrows: false,
                lazyLoad: 'nearby',
                rewind: true
                {#width: '300px'#}
            }).mount();
            {#lightGallery(document.querySelector('lightgallery'));#}
            {#const lightbox = GLightbox({touchNavigation: true});#}
            imgLightbox("img-lightbox-link", {
                rate: 50 /* default: 500 */,
            });
        });
    </script>
{% endblock %}

ads/templates/ad/edit.html
{% extends 'layout.html' %}
{% load i18n %}

{% block content %}

    <h1>{% trans 'Update Ad' %}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% include 'ad/_form.html' %}

{% endblock %}