ads/urls.py
from django.urls import path
from guest_user.decorators import allow_guest_user

from ads import views

app_name = 'ads'
urlpatterns = [
    path('', allow_guest_user(views.IndexView()), name='index'),
    path('search/autocomplete/', allow_guest_user(views.autocomplete), name='autocomplete'),
    path('url/', views.to_external_url, name='to_external_url'),
    path('ads/<str:category>/<str:subcategory>', views.AdsByCategoriesView.as_view(), name='list_by_categories'),
    path('ads/<str:category>', views.AdsByMainCategoryView.as_view(), name='list_by_main_category'),
    path('view/<str:ad_slug>-<int:id>/', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('my_ads/', views.user_ads, name='user_ads'),

]

comohay/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from comohay import settings

urlpatterns = [
    path("convert/", include("guest_user.urls")),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('', include('ads.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/empty-layout.html
{% load compress %}
{% load static %}
{% load i18n %}
{% load meta %}
<!doctype html>
<html lang="en" class="h-100">
    <head {% meta_namespaces %}>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% include 'meta/meta.html' %}

        <meta name="author" content="Daxslab & friends">

        <script type="application/ld+json">
            {
              "@context" : "http://schema.org",
              "@type" : "{{ meta.type }}",
              "name" : "{{ meta.title }}",
              "author" : {
                "@type" : "Company",
                "name" : "Daxslab & friends"
              },
              "image" : "{{ meta.image }}",
              "description": "{{ meta.description }}",
              "url" : "{{ meta.url }}"
            }
        </script>

        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'site.webmanifest' %}">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">

        {% compress css %}
            <link type="text/x-scss" href="{% static 'sass/main.scss' %}" rel="stylesheet">
            <link type="text/css" href="{% static 'fontello/css/fontello.css' %}" rel="stylesheet">
            <link type="text/css" href="{% static 'fontello/css/animation.css' %}" rel="stylesheet">
            <link type="text/css" href="{% static 'fontello/css/fontello-codes.css' %}" rel="stylesheet">
        {% endcompress %}

        {% block css %}
        {% endblock %}

        {% compress js %}
            <!-- Matomo -->
            <script type="text/javascript">
              var _paq = window._paq || [];
              /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
              _paq.push(['trackPageView']);
              _paq.push(['enableLinkTracking']);
              (function() {
                var u="//stats.daxslab.com/";
                _paq.push(['setTrackerUrl', u+'js/']);
                _paq.push(['setSiteId', '1']);
                var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
                g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'js/'; s.parentNode.insertBefore(g,s);
              })();
            </script>
            <!-- End Matomo Code -->
        {% endcompress %}

    </head>
    <body>

        {% block essence %}
        {% endblock %}

        <footer class="footer">
          <div class="container center-content">
              <ul class="list-inline list-social">
            <li><a href="https://facebook.com/comohayads" target="_blank">Facebook</a></li>
            <li><a href="https://twitter.com/comohayads" target="_blank">Twitter</a></li>
            <li><a href="https://t.me/comohayads" target="_blank">Telegram</a></li>
            <li><a href="https://wa.me/15519005717" target="_blank">WhatsApp</a></li>
          </ul>
          <p class="credits">Desarrollado por <a href="https://www.daxslab.com" target="_blank">Daxslab</a> & friends</p>
          </div>
        </footer>


        {% compress js %}
            <script type="text/javascript" src="{% static 'js/main.js' %}" async></script>
        {% endcompress %}

        {% block js %}
        {% endblock %}

    </body>
</html>

templates/layout.html
{% extends 'empty-layout.html' %}
{% load compress %}
{% load static %}
{% load i18n %}

{% block essence %}
    <header>
        <nav class="navigation">
            <section class="container">
                <a class="navigation-title" href="{% url 'ads:index' %}">
                    <h1 class="title">Como Hay</h1>
                </a>
                <ul class="navigation-list float-right">
                    <li class="navigation-item"><a class="navigation-link"
                                                   href="{% url 'ads:index' %}">{% trans 'Index' %}</a></li>
                    <li class="navigation-item"><a class="navigation-link"
                                                   href="{% url 'ads:create' %}">{% trans 'Add ad' %}</a></li>
                    {% if user.is_authenticated %}
                        <li class="navigation-item"><a class="navigation-link"
                                                       href="{% url 'ads:user_ads' %}">{% trans 'My Ads' %}</a></li>
                        <li class="navigation-item"><a class="navigation-link"
                                                       href="{% url 'account_logout' %}">{% trans 'Logout' %}</a></li>
                    {% else %}
                        <li class="navigation-item"><a class="navigation-link"
                                                       href="{% url 'account_login' %}">{% trans 'Login' %}</a></li>
                    {% endif %}
                </ul>
            </section>
        </nav>
    </header>


    <main role="main">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    {#        <footer class="footer">#}
    {#            <div class="container">#}
    {#                <span class="text-muted">Place footer content here.</span>#}
    {#            </div>#}
    {#        </footer>#}

{% endblock %}