ads/urls.py
from django.urls import path
from guest_user.decorators import allow_guest_user

from ads import views

app_name = 'ads'
urlpatterns = [
    path('', allow_guest_user(views.IndexView()), name='index'),
    path('search/autocomplete/', allow_guest_user(views.autocomplete), name='autocomplete'),
    path('url/', views.to_external_url, name='to_external_url'),
    path('ads/<str:category>/<str:subcategory>', views.AdsByCategoriesView.as_view(), name='list_by_categories'),
    path('ads/<str:category>', views.AdsByMainCategoryView.as_view(), name='list_by_main_category'),
    path('view/<str:ad_slug>-<int:id>/', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('my_ads/', views.user_ads, name='user_ads'),

]

comohay/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from comohay import settings

urlpatterns = [
    path("convert/", include("guest_user.urls")),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('', include('ads.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models/adimages.py
from django.db import models
from django.db.models.signals import post_init, post_save, pre_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from ads.models.ad import Ad


class AdImage(models.Model):
    ad = models.ForeignKey(Ad, default=None, on_delete=models.CASCADE, verbose_name=_('Ad'))
    image = models.ImageField(verbose_name=_('Image'))

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')


@receiver(post_init, sender=AdImage)
def backup_image_path(sender, instance, **kwargs):
    if (instance.id is not None):
        instance._current_image_file = instance.image


@receiver(post_save, sender=AdImage)
def delete_old_image(sender, instance, **kwargs):
    if hasattr(instance, '_current_image_file'):
        if instance._current_image_file.path != instance.image.path:
            instance._current_image_file.delete(save=False)


@receiver(pre_delete, sender=AdImage)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)

ads/forms/adform.py
from categories.models import Category
from django.forms import ModelForm
from django_filters.fields import ModelChoiceField

from ads.models.ad import Ad


class AdForm(ModelForm):

    category = ModelChoiceField(Category.objects.exclude(parent=None).all())

    class Meta:
        model = Ad
        exclude = [
            'slug',
            'external_source',
            'external_id',
            'external_url',
            'created_at',
            'updated_at',
            'created_by',
            'created_at',
        ]

ads/forms/adimageform.py
from django.forms import ModelForm, ImageField, FileInput
from django.utils.translation import gettext_lazy as _
from ads.models.adimages import AdImage


class AdImageForm(ModelForm):

    image = ImageField(label=_('Image'))

    class Meta:
        model = AdImage
        fields = ('image',)

ads/forms/adsearchform.py
import sys

from haystack.forms import ModelSearchForm
from haystack.inputs import AltParser

from ads.models import Ad, Province
from django import forms


class AdSearchForm(ModelSearchForm):
    provinces = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Province.objects.all(),
        to_field_name='name'
    )

    price_from = forms.IntegerField(required=False)
    price_to = forms.IntegerField(required=False)
    price_currency = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.sqs = None

    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        q = self.cleaned_data['q']

        provinces = self.cleaned_data['provinces']
        price_from = self.cleaned_data['price_from']
        price_to = self.cleaned_data['price_to']
        price_currency = self.cleaned_data['price_currency']

        # boosting of 1.5 for every term that appears in the title
        # TODO: improve this by overriding the solr backend method build_alt_parser_query in order to avoid to do the
        #  escaping twice. It will be recommended in order to avoid triple escaping in the boost query(bq) to build the
        #  query with the defType parameter instead of the LocalParams syntax that is currently being in use by the
        #  build_alt_parser_query method.
        bq = self.create_boosting_query(q)

        # boost multiplier by age. This solr function will return a number between 1 an 0, the older the ad the lower
        # the number. Please refer to
        #   https://lucene.apache.org/solr/guide/7_7/function-queries.html
        #   https://lucene.apache.org/core/6_6_0/queries/org/apache/lucene/queries/function/valuesource/ReciprocalFloatFunction.html and
        #   https://www.youtube.com/watch?v=3E8jOUgj6L8to
        boost = "recip(ms(NOW,external_created_at),3.16e-11,1,1)"

        pf = "title^2.5 description^0.15"
        pf3 = "title^1.5 description^0.10"
        pf2 = "title^0.5 description^0.05"

        sqs = self.searchqueryset.filter(
            content=AltParser('edismax', q, bq=bq, boost=boost, pf=pf, pf3=pf3, pf2=pf2, ps=2, ps3=2, ps2=1))

        if provinces.count() > 0:
            sqs = sqs.filter_and(province__in=provinces.values_list('name', flat=True))

        if price_from and price_to:
            sqs = sqs.filter_and(price__range=[price_from, price_to])
        elif price_from:
            sqs = sqs.filter_and(price__range=[price_from, sys.maxsize])
        elif price_to:
            sqs = sqs.filter_and(price__range=[0, price_to])

        if price_from or price_to:
            sqs = sqs.filter_and(currency_iso=price_currency)

        # TODO: add flag to allow to search trough removed ads
        if True:
            sqs = sqs.filter_and(is_deleted=False)

        if self.load_all:
            sqs = sqs.load_all()

        return sqs.models(Ad)

    def create_boosting_query(self, query):
        # Removing '"' because its not necessary for query boosting
        query = query.replace('"', '')

        clean_q = self.triple_clean(query)
        clean_q = clean_q.replace("'", "\\\\'")

        # this will add the field to search and the boosting value for each term.
        # Eg. 'split royal' -> 'title:split^1.5 title:royal^1.5 description:split^1.1 description:royal^1.1'
        return 'title:' + clean_q.replace(' ', '^1.5 title:') + '^1.5' + ' description:' + clean_q.replace(' ',
                                                                                                           '^0.1 description:') + '^0.1'

    def triple_clean(self, query_fragment):
        """
        Provides a mechanism for sanitizing user input before presenting the
        value to the backend.

        A basic (override-able) implementation is provided.
        """
        backend = self.searchqueryset.query.backend

        if not isinstance(query_fragment, str):
            return query_fragment

        words = query_fragment.split()
        cleaned_words = []

        for word in words:
            if word in backend.RESERVED_WORDS:
                word = word.replace(word, word.lower())

            for char in backend.RESERVED_CHARACTERS:
                word = word.replace(char, "\\\\\\\\%s" % char)

            cleaned_words.append(word)

        return " ".join(cleaned_words)

ads/views.py
import logging
import re
from encodings.base64_codec import base64_decode

from actstream import action
from categories.models import Category
from django.contrib.auth.decorators import login_required
from django.core.cache import caches
from django.core.exceptions import ValidationError
from django.forms import modelformset_factory, inlineformset_factory
from django.http import HttpResponseRedirect, Http404, HttpResponseBadRequest, JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator

from django_filters.views import FilterView
from guest_user.decorators import allow_guest_user
from haystack.views import SearchView
from meta.views import Meta
from rest_framework.utils import json
from text_unidecode import unidecode

from ads.actions import ACTION_FOLLOW_EXTERNAL_AD, ACTION_VIEW_AD, ACTION_SEARCH_AD
from ads.filters.ad_filter import AdFilter
from ads.forms.adform import AdForm
from ads.forms.adimageform import AdImageForm
from ads.forms.adsearchform import AdSearchForm
from ads.helpers.telegrambot import TelegramBot
from ads.models import UserSearch, Province
from ads.models.ad import Ad
from ads.models.adimages import AdImage
from comohay import settings

logger = logging.getLogger(__name__)


class IndexView(SearchView):
    template = 'ad/index.html'

    def __init__(self, template=None, load_all=True, form_class=None, searchqueryset=None, results_per_page=None):
        super().__init__(template, load_all, form_class, searchqueryset, results_per_page)
        if form_class is None:
            self.form_class = AdSearchForm

    def __call__(self, request):
        cache = caches['search']
        path = request.get_full_path()

        self.request = request
        self.form = self.build_form()
        self.query = self.get_query()
        self.results = self.get_results()

        response = cache.get(path)
        if not response:
            response = self.create_response()
            cache.set(path, response, settings.CACHE_SEARCH_RESPONSE_SECONDS)
        if self.query != '' and not self.request.GET.get('page', False) and not request.user.is_anonymous:
            user_search = UserSearch(user=request.user, search=self.query,
                                     autosuggestion=bool(request.GET.get('a', False)))
            user_search.save()
            action.send(request.user, verb=ACTION_SEARCH_AD, target=user_search)
        return response

    def get_context(self):
        context = super().get_context()
        result_count = self.results.count()
        #TODO: solr is throwing a java.lang.NumberFormatException when there is no results, but it seems to not have any
        # negative effect, it could be the Spellchecker
        context['index_count'] = result_count if self.query != '' else Ad.objects.count()

        context['all_provinces'] = Province.objects.all()
        context['all_currencies'] = Ad.ALLOWED_CURRENCIES

        if self.query:
            context['price_from'] = self.form.cleaned_data['price_from']
            context['price_to'] = self.form.cleaned_data['price_to']
            context['price_currency'] = self.form.cleaned_data['price_currency']
            context['selected_provinces'] = self.form.cleaned_data['provinces']

        base_query_dict = self.request.GET.copy()
        if 'page' in base_query_dict:
            del base_query_dict['page']
        context['base_query'] = base_query_dict.urlencode()

        # Before split the query its necessary to remove the '"' characters because those are part of the syntax to
        # phrase query
        query_split = self.query.replace('"', '').split(' ')

        def find_missing_terms(search_result):
            missing_terms = []
            for term in query_split:
                if not re.search(re.escape(unidecode(term)), unidecode(search_result.text), re.IGNORECASE):
                    missing_terms.append(term)

            search_result.__dict__['missing_terms'] = missing_terms
            return search_result

        context['page'].object_list = map(find_missing_terms, context['page'].object_list)

        meta = Meta(
            keywords=['indexado de clasificados en cuba', 'búsqueda de clasificados en cuba',
                      'cuba indexado de clasificados', 'cuba búsqueda de clasificados',
                      'indexado de anuncios en cuba', 'búsqueda de anuncios en cuba',
                      'cuba indexado de anuncios', 'cuba búsqueda de anuncios'
                      ],
            image=settings.STATIC_URL + 'logo-vertical-adjusted.png',
            image_width=600,
            image_height=600,
            url=self.request.get_full_path(),
            title=settings.META_SITE_NAME,
            description='La manera más eficiente de buscar clasificados en Cuba, rápido y ligero. Indexamos constantemente los sitos más populares de anuncios en nuestro país.',
        )

        if self.query != '':
            meta.title = '{} - {}'.format(self.query, settings.META_SITE_NAME)
            meta.description = "Consulta los resultados para \"{}\" que hemos encontrado. Indexamos constantemente los sitios cubanos de anuncios más populares para ofrecerte los mejores resultados.".format(
                self.query)

        context['meta'] = meta
        return context


def autocomplete(request):
    query = request.GET.get('q', '')

    suggestions = settings.autocomplete.search(query, max_cost=3, size=7)

    for pos in range(len(suggestions)):
        if type(suggestions[pos]) != str:
            suggestions[pos] = ' '.join(suggestions[pos])

    the_data = json.dumps({
        'results': suggestions
    })

    return HttpResponse(the_data, content_type='application/json')


class AdsByMainCategoryView(FilterView):
    paginate_by = 20
    model = Ad
    template_name = 'ad/ads.html'
    filterset_fields = '__all__'
    category: Category

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.category = get_object_or_404(Category, slug=self.kwargs['category'], parent=None)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['category'] = self.category

        return context

    @method_decorator(allow_guest_user)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class AdsByCategoriesView(FilterView):
    paginate_by = 20
    model = Ad
    template_name = 'ad/ads.html'
    filterset_fields = '__all__'
    category: Category
    subcategory: Category

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.category = get_object_or_404(Category, slug=self.kwargs['category'])
        try:
            self.subcategory = Category.objects.filter(slug=self.kwargs['subcategory'], parent=self.category.id).get()
        except Category.DoesNotExist:
            raise Http404('No categories matches the given query.')

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-created_at')
        return queryset.filter(category=self.subcategory.id)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['category'] = self.category
        context['subcategory'] = self.subcategory

        return context

    @method_decorator(allow_guest_user)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@allow_guest_user
def detail(request, id, ad_slug):
    ad = get_object_or_404(Ad, id=id, slug=ad_slug)
    action.send(request.user, verb=ACTION_VIEW_AD, target=ad)
    return render(request, 'ad/detail.html', {'ad': ad})


@allow_guest_user
# @csrf_exempt
def create(request):
    image_form_set = modelformset_factory(AdImage, form=AdImageForm, extra=3)

    if request.method == 'POST':
        ad_form = AdForm(request.POST)
        ad_image_formset = image_form_set(
            request.POST,
            request.FILES,
            queryset=AdImage.objects.none()
        )

        if ad_form.is_valid() and ad_image_formset.is_valid():
            ad = ad_form.save()
            for form in ad_image_formset.cleaned_data:
                if 'image' in form:
                    image = form['image']
                    ad_image = AdImage(ad=ad, image=image)
                    ad_image.save()

            try:
                TelegramBot.broadcast_ad(ad, request)
            except Exception as e:
                logger.error('Error broadcasting AD: ' + str(e))

            if request.user.is_authenticated:
                return HttpResponseRedirect('/my_ads')
            return HttpResponseRedirect('/')
    else:
        ad_form = AdForm()
        ad_image_formset = image_form_set(queryset=AdImage.objects.none())
    return render(request, 'ad/create.html', {'ad_form': ad_form, 'ad_image_formset': ad_image_formset})


@allow_guest_user
def to_external_url(request):
    url = request.GET.get('url')
    ref = request.GET.get('ref')
    request_ad = request.GET.get('ad')
    from_url = base64_decode(bytes(ref, 'utf-8'))[0].decode('utf-8')
    ad_id = base64_decode(bytes(request_ad, 'utf-8'))[0].decode('utf-8')
    ad = get_object_or_404(Ad, id=ad_id)
    if not url or not from_url or not from_url.startswith(request.build_absolute_uri('/')) or not ad:
        return HttpResponseBadRequest()
    response = HttpResponseRedirect(url)
    response['Referer'] = from_url
    if not request.user.is_anonymous:
        action.send(request.user, verb=ACTION_FOLLOW_EXTERNAL_AD, target=ad)
    return response


@login_required
def user_ads(request):

templates/ad/ads.html
{% extends 'layout.html' %}

{% block content %}

    <h1>Como Hay</h1>
    {% if subcategory %}
        <h2>{{ subcategory.name }}</h2>
    {% elif category %}
        <h2>{{ category.name }}</h2>
    {% endif %}

    {% if object_list %}
        <ul>
        {% for ad in object_list %}
            <li><a href="{{ ad.get_absolute_url }}" {% if ad.external_source %}target="_blank"{% endif %}>{{ ad.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No se encontraron resultados.</p>
    {% endif %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock %}

templates/ad/create.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1>Create AD</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form id="create_ad" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ ad_form|crispy }}

    <script>
        let province_select = document.getElementById('id_province');
        let municipality_select = document.getElementById('id_municipality');

        let selectListElement = function(id, valueToSelect){
            let element = document.getElementById(id);
            element.value = valueToSelect;
        };

        province_select.addEventListener('change', function (e) {
            let elements = '<option value="" selected="">---------</option>';
            municipality_select.innerHTML = elements;

            var r = new XMLHttpRequest();
            r.open("GET", "/api/v1/municipalities/?size=200&province="+province_select.value, true);
            r.onreadystatechange = function () {
                if (r.readyState != 4 || r.status != 200) return;
                JSON.parse(r.responseText).results.forEach(function (item) {
                    elements += `<option value="${item.id}">${item.name}</option>`
                });
                municipality_select.innerHTML = elements;
            };
            r.send();
        });

        municipality_select.addEventListener('change', function (e) {
            var r = new XMLHttpRequest();
            r.open("GET", "/api/v1/provinces/?municipality__id="+municipality_select.value, true);
            r.onreadystatechange = function () {
                if (r.readyState != 4 || r.status != 200) return;

                let data = JSON.parse(r.responseText);
                if (data.results && data.results.length > 0){
                    province_select.value = data.results[0].id;
                } else {
                    province_select.value = null;
                    province_select.selectedIndex = 0;
                }
            };
            r.send();
        });


    </script>

    {{ ad_image_formset.management_form }}
    {% for form in ad_image_formset %}
        {{ form|crispy }}
    {% endfor %}

    <input type="submit" value="Submit">
</form>

{% endblock %}

templates/ad/detail.html
{% extends 'layout.html' %}
{% load more_like_this %}

{% block content %}
    <h1>{{ ad.title }}</h1>


    {% if ad.adimage_set.all %}

            {% for ad_image in ad.adimage_set.all %}

                    <img src="{{ ad_image.image.url }}" class="img-rounded" alt="">

            {% endfor %}

    {% endif %}

    <p>{{ ad.description }}</p>

    {% if ad.price %}
    <p>{{ ad.price }}</p>
    {% endif %}

    {% more_like_this ad as related_contents limit 5 %}
    {% if related_contents %}
        <h3>También le puede interesar:</h3>
        {% for related_content in related_contents %}
            <li><a href="{{ related_content.object.get_absolute_url }}">{{ related_content.object.title }}</a></li>
        {% endfor %}
    {% endif %}



{% endblock %}

templates/ad/index.html
{% extends 'layout.html' %}

{% block content %}

    <h1>Como Hay</h1>

    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <form method="get" action="." class="card card-sm">
                <div class="card-body row no-gutters allign-items-center">
                    <div class="col-auto">
                        <i></i>
                    </div>
                    <div class="col">
                        <input placeholder="Buscar" class="form-control form-control-lg form-control-borderless" value="{{ query }}" type="search" name="q" id="id_q">
                        {% if suggestion and query != suggestion %}
                        <div>
                            <p>Quizá quiso decir: <a href="{% url 'ads:index' %}?q={{ suggestion }}">{{ suggestion }}</a></p>
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-auto">
                        <input type="submit" value="Buscar" class="btn btn-lg btn-success">
                    </div>
                </div>
            </form>
        </div>
    </div>


        {% if query %}
            <h2>Resultados</h2>

            {% for result in page.object_list %}
                {% include 'ad/_search_result.html' %}
            {% empty %}
                <p>No se encontraron resultados.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {% for parent_category in parent_categories %}
                {% if parent_category.children.count %}
                    <h4><a href="{% url 'ads:list_by_main_category' parent_category.slug %}">{{ parent_category.name }}</a></h4>
                    <ul>
                    {% for subcategory in parent_category.children.all %}
                        <li><a href="{% url 'ads:list_by_categories' parent_category.slug subcategory.slug %}">{{ subcategory.name }}</a></li>
                    {% endfor %}
                    </ul>

                {% endif %}
            {% endfor %}

        {% endif %}

{% endblock %}